  name: Docker CI

on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Checkout repo
uses: actions/checkout@v3

- name: Build and run container
run: |
docker build -t myapp:latest .
docker run -d -p 5000:5000 --name test_container myapp:latest
sleep 5
curl -f http://localhost:5000
docker stop test_container

